version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432
  backend:
    build: ../backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - static:/static
    depends_on:
      - db
  nginx:
    build: ../infra
    ports:
      - "10000:80"
    volumes:
      - ./docs:/api/docs/
      - static:/staticfiles
      - media:/media
